name = "longyucomments"
main = "src/worker.js"
workers_dev = true
compatibility_date = "2025-06-27"

routes = [
  "api.long-yu.net/*"
]

[observability]
enabled = true

[[kv_namespaces]]
id = "159726cad77c4ceb990080952836d25a"
binding = "COMMENTS_KV"

[[r2_buckets]]
binding = "IMAGES_R2_BUCKET"
bucket_name = "longyu-comment-images"
preview_bucket_name = "longyu-comment-images"