name = "longyucomments"
main = "src/worker.js"
workers_dev = true
compatibility_date = "2025-06-27"

[observability]
enabled = true

[[kv_namespaces]]
id = "159726cad77c4ceb990080952836d25a"
binding = "COMMENTS_KV"
